<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2020/08/03 00:24:31
sfConfig::add(array(
  'mod_securityauthentication_enabled' => true,
  'mod_securityauthentication_view_class' => 'sfPHP',
));
