<?php
// auto-generated by sfSecurityConfigHandler
// date: 2020/08/03 00:26:33
$this->security = array (
  'viewbuzzimage' => 
  array (
    'is_secure' => true,
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
