<?php
// auto-generated by sfSecurityConfigHandler
// date: 2020/08/03 00:24:31
$this->security = array (
  'all' => 
  array (
    'is_secure' => false,
  ),
  'securityauthenticationconfigure' => 
  array (
    'is_secure' => true,
  ),
  'requestpasswordresetcode' => 
  array (
    'is_secure' => true,
  ),
  'resetpassword' => 
  array (
    'is_secure' => true,
  ),
);
